plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'maven-publish'
}

android {
    namespace "com.cl.serialportlibrary"
    compileSdk 36
    ndkVersion '27.0.12077973'

    defaultConfig {
        minSdk 21
        targetSdk 36
        versionCode 508
        versionName "5.0.8"
        consumerProguardFiles "consumer-rules.pro"
        
        externalNativeBuild {
            cmake {
                arguments "-DANDROID_PLATFORM=android-21"
            }
        }
        ndk {
            abiFilters 'arm64-v8a', 'armeabi-v7a', 'x86', 'x86_64'
        }
    }
    
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
        freeCompilerArgs += ['-Xjvm-default=all']
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    externalNativeBuild {
        cmake {
            path "src/main/cpp/CMakeLists.txt"
        }
    }
}

dependencies {
    implementation libs.kotlinx.coroutines.core
    testImplementation libs.junit
}

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                groupId = 'com.github.cl-6666'
                artifactId = 'serialPort'
                version = '5.0.8'
                
                from components.release
                
                pom {
                    name = 'SerialPort Library'
                    description = 'Android Serial Port Library with JNI support'
                    url = 'https://github.com/cl-6666/serialPort'
                    
                    licenses {
                        license {
                            name = 'The Apache License, Version 2.0'
                            url = 'http://www.apache.org/licenses/LICENSE-2.0.txt'
                        }
                    }
                    
                    developers {
                        developer {
                            id = 'cl-6666'
                            name = 'cl-6666'
                        }
                    }
                    
                    scm {
                        connection = 'scm:git:git://github.com/cl-6666/serialPort.git'
                        developerConnection = 'scm:git:ssh://github.com:cl-6666/serialPort.git'
                        url = 'https://github.com/cl-6666/serialPort/tree/master'
                    }
                }
            }
        }
    }
}
